name: Replace version
description: Replace package version in Cargo.toml
inputs:
  version:
    description: Version to set
    required: true
runs:
  using: composite
  steps:
    - name: Replace version
      shell: bash
      # There isn't a sed command working on all platforms to replace string in a file, so use perl.
      run: perl -i -pe's/0.0.0-dev/${{ inputs.version }}/' Cargo.toml
