name: Add Target
description: Add target via rustup
inputs:
  target:
    description: Target triple
    required: true
runs:
  using: composite
  steps:
    - name: Add target
      shell: bash
      run: rustup target add ${{ inputs.target }}
