workspace = { members = ["examples/wasi/get_memory_info", "examples/wasi/get_system_info"] }
[package]
name = "psh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.151"
clap = { version = "4.4.5", features = ["derive", "wrap_help"] }
tonic = "0.10"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
nix = "0.20.0"
num_cpus = "1.16.0"
netdata-plugin = "0.2.0"
wasmtime = "18.0.2"
wasmtime-wasi = "18.0.2"
wit-bindgen = "0.20.0"
uname = "0.1.1"

[build-dependencies]
tonic-build = "0.10"
