[package]
name = "psh-system"
edition = "2021"
version.workspace = true

[dependencies]
anyhow = "1.0.86"
once_cell = "1.19.0"
procfs = "0.16.0"
thiserror = "1.0.61"
uname = "0.1.1"
which = "6.0.1"

[dev-dependencies]
num_cpus = "1.16.0"
