[package]
name = "host-op-ebpf"
version.workspace = true
edition = "2021"

[dependencies]
anyhow = "1.0.86"
errno = "0.3.9"
lazy_static = "1.5.0"
libbpf-rs = "0.23.3"
libc = "0.2.155"
log = "0.4.21"
ouroboros = "0.18.4"
wasmtime = "22.0.0"
wasmtime-wasi = "22.0.0"
