[package]
name = "ebpf"
edition = "2021"
version.workspace = true

[dependencies]
anyhow = "1.0.86"
gimli = "0.30.0"
memmap2 = "0.9.4"
object = "0.36.0"
typed-arena = "2.0.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html