name: Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  build:
    name: Build Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        # TODO: do we want to support musl?
        target: [x86_64-unknown-linux-gnu]

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - uses: actions/checkout/@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0

      - name:  Show environment information
        uses: ./.github/actions/show-env

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Build Psh
        uses: ./.github/actions/build
        with:
          target: ${{ matrix.target }}
          release: false
