name: Clippy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  clippy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - uses: actions/checkout/@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Show env
        uses: ./.github/actions/show-env

      - name: Setup protoc
        uses: arduino/setup-protoc@v3

      - name: Setup build cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Clippy
        uses: ./.github/actions/clippy
