name: Rustfmt

on:
  push:
  pull_request:

jobs:
  rustfmt:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: Show environment information
        shell: bash
        run: |
          cargo -V
          cargo fmt -- -V
          rustc -V
          uname -a

      - name: Check fmt
        uses: ./.github/actions/rustfmt
