name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        target: [x86_64-unknown-linux-gnu]

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - uses: actions/checkout/@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Install cargo-component
        run: cargo binstall cargo-component

      - name: Show env
        uses: ./.github/actions/show-env

      - name: Setup build cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Setup protoc
        uses: arduino/setup-protoc@v3

      - name: Build
        uses: ./.github/actions/build
        with:
          target: ${{ matrix.target }}
          release: false

      - name: Test
        uses: ./.github/actions/test
