name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - uses: actions/checkout/@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0
          targets: wasm32-wasip1

      - name: Install cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Show env
        uses: ./.github/actions/show-env

      - name: Setup build cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Install cargo-component
        run: cargo install cargo-component

      - name: Setup protoc
        uses: arduino/setup-protoc@v3

      - name: Build test resource
        run:
          git submodule update --init --recursive
          ./scripts/build-test-resources.sh

      - name: Test
        uses: ./.github/actions/test
